- name: Install NGINX
  yum:
    name: nginx
    state: present

- name: Copy NGINX config
  template:
    src: sadhix.conf.j2
    dest: /etc/nginx/conf.d/sms.conf
  notify: restart nginx

- name: Remove default NGINX config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Start and enable NGINX
  service:
    name: nginx
    state: started
    enabled: yes

