--- #handler=worker  notify=inform
- hosts: all
  tasks:
  - name: apache latest version
    yum: name=httpd state=latest
    notify: 
      - restart apache
    handlers:
      - name: restart apache
      - service: name=httpd state=restarted
